### ISSUE TITLE
BUG: summary report code fails to run for Python 3.9

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#502]
When executing the following command:

`python -m darshan summary /path/to/log.darshan`

in a Python 3.9 environment, I get the following error:
```
Traceback (most recent call last):
  File "/Users/nawtrey/opt/anaconda3/envs/pydarshan-dev/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/nawtrey/opt/anaconda3/envs/pydarshan-dev/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/nawtrey/darshan_install/darshan/darshan-util/pydarshan/darshan/__main__.py", line 3, in <module>
    main()
  File "/Users/nawtrey/darshan_install/darshan/darshan-util/pydarshan/darshan/cli/__init__.py", line 164, in main
    mod.main(args)
  File "/Users/nawtrey/darshan_install/darshan/darshan-util/pydarshan/darshan/cli/summary.py", line 218, in main
    with importlib_resources.path(darshan.cli, "") as path:
  File "/Users/nawtrey/opt/anaconda3/envs/pydarshan-dev/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/nawtrey/opt/anaconda3/envs/pydarshan-dev/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/Users/nawtrey/darshan_install/darshan/darshan-util/pydarshan/darshan/cli'
```

I've confirmed this on my own fork while testing the CLI for other reasons. It passes for our Python 3.7 and 3.8 runners, but only passes for 3.9 if we adopt the following change in `darshan/cli/summary.py`:

```python
with importlib_resources.path(darshan.cli, "base.html") as base_path:
    # load a template object using the base template
    template = Template(filename=str(base_path))
```

**Comment by tylerjereddy** [comment]
Sounds like there should be tests for running the report in CI per #488 and #489. Also, Python 3.10 comes out next week, so testing will likely be expanded then. Anyway, definitely need tests running...

**Comment by nawtrey** [comment]
Agreed, I discovered this issue while working on those issues.

**Comment by tylerjereddy** [comment]
Another question is whether [`importlib_resources`](https://pypi.org/project/importlib-resources/) should be used for the main library like it is for the test suite to handle the Python < 3.9 cases. Extra runtime dependency vs. how invasive the fix/shim is.

**Comment by nawtrey** [comment]
Yeah, I don't see a strong reason to keep `path` and `base_path` separate at the moment which is why I suggested changing `main()`, but I don't feel strongly either way.

**Comment by kevin-harms** [comment]
Adopting changes to support the newer python versions makes sense to me.

**Comment by carns** [comment]
> Adopting changes to support the newer python versions makes sense to me.

Agreed; I'm fine with whatever the simplest solution is here to get us going with 3.9.

**Comment by tylerjereddy** [comment]
One point of caution here--`importlib.resources` was new in Python `3.7` and we support `3.6` now, so my suggestion of using the backport project above may have merit.
