### ISSUE TITLE
Instructions for working pyDarshan on RHEL variants

### ISSUE THREAD

**Issue by dcsouthwick** [darshan-hpc/darshan#552]
Hello,

After struggling to follow what should otherwise be a simple "pip(3) install darshan", it seems all current instructions for pyDarshan seem either outdated or inaccurate for RHEL variants. Could you clarify what is missing here?

I've provided a Dockerfile as an starting example:
```dockerfile
FROM centos:8
RUN dnf groupinstall -y "Development Tools"; \
    dnf install -y python3 python3-devel libjpeg-devel python3-cffi python3-numpy texlive-latex; \
    curl -LO ftp://ftp.mcs.anl.gov/pub/darshan/releases/darshan-3.3.1.tar.gz; \
    tar zxvf darshan-3.3.1.tar.gz && cd darshan-3.3.1/darshan-util; \
    ./configure && make -j && make install; \
    python3 -m pip install darshan
```

Build this example with docker, and try and use pyDarshan:
```python3
>import darshan

**Comment by tylerjereddy** [comment]
Do you need the latest version of `darshan` as opposed to the pre-built binary wheels installable via `pip install darshan` (pulling from PyPI instead of building from source)?

Source installs typically need `LD_LIBRARY_PATH` to be set to point to that shared object. There's an example in our CI here: https://github.com/darshan-hpc/darshan/blob/pydarshan-devel/.github/workflows/main_ci.yml#L66

Something like `export LD_LIBRARY_PATH=$PWD/darshan_install/lib`.

**Comment by dcsouthwick** [comment]
I guess I'm a bit confused at your comment, as neither of these seem to work.

If I understand you correctly,`pip3 install darshan` should provide a working module (as it uses the pre-built wheels), however it seems to not do so. Example:
```Dockerfile
FROM centos:8
RUN dnf groupinstall -y "Development Tools"; dnf install -y python3-devel libjpeg-devel; python3 -m pip install darshan
```
```sh
python3
>>> import darshan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/darshan/__init__.py", line 19, in <module>
    from darshan.report import DarshanReport
  File "/usr/local/lib64/python3.6/site-packages/darshan/report.py", line 10, in <module>
    import darshan.backend.cffi_backend as backend
  File "/usr/local/lib64/python3.6/site-packages/darshan/backend/cffi_backend.py", line 47, in <module>
    libdutil = find_utils(ffi, libdutil)
  File "/usr/local/lib64/python3.6/site-packages/darshan/discover_darshan.py", line 216, in find_utils
    raise RuntimeError('Could not find libdarshan-util.so! Is darshan-util installed? Please ensure one of the the following: 1) export LD_LIBRARY_PATH=<path-to-libdarshan-util.so>, or 2) darshan-parser can found using the PATH variable, or 3) pkg-config can resolve pkg-config --path darshan-util, or 4) install a wheel that includes darshan-utils via pip.')
RuntimeError: Could not find libdarshan-util.so! Is darshan-util installed? Please ensure one of the the following: 1) export LD_LIBRARY_PATH=<path-to-libdarshan-util.so>, or 2) darshan-parser can found using the PATH variable, or 3) pkg-config can resolve pkg-config --path darshan-util, or 4) install a wheel that includes darshan-utils via pip.
```


If I try and install from source (even using stable 3.3.1 from your website... logically this should be the same "working" version 3.3.1 from pip):
```dockerfile
RUN dnf groupinstall -y "Development Tools"; \
    dnf install -y python3-devel libjpeg-devel python3-cffi python3-numpy texlive-latex; \
    curl -LO ftp://ftp.mcs.anl.gov/pub/darshan/releases/darshan-3.3.1.tar.gz; \
    tar zxvf darshan-3.3.1.tar.gz && cd darshan-3.3.1/darshan-util; \
    ./configure && make -j && make install; \
    cd pydarshan; \
    python3 -m pip install matplotlib==3.3.4 cython# workaround for most of HEP using RHEL with old python
    make && make install
```
now trying to run:
```sh
$ python3
>>> import darshan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/darshan/__init__.py", line 19, in <module>
    from darshan.report import DarshanReport
  File "/usr/local/lib64/python3.6/site-packages/darshan/report.py", line 10, in <module>
    import darshan.backend.cffi_backend as backend
  File "/usr/local/lib64/python3.6/site-packages/darshan/backend/cffi_backend.py", line 47, in <module>
    libdutil = find_utils(ffi, libdutil)
  File "/usr/local/lib64/python3.6/site-packages/darshan/discover_darshan.py", line 216, in find_utils
    raise RuntimeError('Could not find libdarshan-util.so! Is darshan-util installed? Please ensure one of the the following: 1) export LD_LIBRARY_PATH=<path-to-libdarshan-util.so>, or 2) darshan-parser can found using the PATH variable, or 3) pkg-config can resolve pkg-config --path darshan-util, or 4) install a wheel that includes darshan-utils via pip.')
RuntimeError: Could not find libdarshan-util.so! Is darshan-util installed? Please ensure one of the the following: 1) export LD_LIBRARY_PATH=<path-to-libdarshan-util.so>, or 2) darshan-parser can found using the PATH variable, or 3) pkg-config can resolve pkg-config --path darshan-util, or 4) install a wheel that includes darshan-utils via pip.
```

Your import error message claims to be looking for `darshan-util`, which the results of `make install` in the first post show is never built nor installed. The error message claims to be looking for `libdarshan-util.so`, again, never built by make or installed. 

If this should work from binary wheels via `pip3 install` with no other action from the users, I think you might be missing requirements?

**Comment by tylerjereddy** [comment]
I can reproduce using your Docker example. For the binary wheel I had to use `export LD_LIBRARY_PATH=/usr/local/lib64/python3.6/site-packages/darshan.libs`.

I don't know if running `pip` as root might be causing issues, though it certainly results in a warning `WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`.

In my hands the shared object gets a bit of a weird name: ` /usr/local/lib64/python3.6/site-packages/darshan.libs/libdarshan-util-0ca4caca.so`

If I get some time I'll try to check if the same thing happens in a venv.

**Comment by tylerjereddy** [comment]
As an update here, `python -m pip install darshan` worked perfectly for me in your docker setup above if I first created and installed a virtualenv to avoid running the install as `root`.

i.e.,

```
python3 -m pip install virtualenv
python3 -m virtualenv python36_venv
source /python36_venv/bin/activate
python -m pip install darshan
# regular import works fine now
```

I imagine this is a bit confusing, but also the reason the warning is emitted above when running as `root`. I don't know if other Python packages suffer from this issue with their wheels, though I would suspect the ecosystem would target non-root installs for the most part.

**Comment by dcsouthwick** [comment]
Hmm - a consistent way to use this without retooling everything to venv would be neat - would make including pydarshan to other containers (jupyter etc) much easier. It seems it's more involved than simply setting the LD path to the correctly named lib however:
```
# mv libdarshan-util-0ca4caca.so libdarshan-util.so
# mv libz-eb09ad1d.so.1.2.3 libz.so
# export LD_LIBRARY_PATH=/opt/conda/lib/python3.9/site-packages/darshan.libs
# python3 -c 'import darshan' 
'Could not find libdarshan-util.so! Is darshan-util installed?...Please ensure one of the the following: 1) export LD_LIBRARY_PATH=<path-to-libdarshan-util.so>...
```

**Comment by tylerjereddy** [comment]
> Hmm - a consistent way to use this without retooling everything to venv would be neat 

You don't have to retool to `venv`, you should just avoid running commands as the `root` user, which is a good practice in most cases anyway. If you really are convinced that what you want is to run as `root`, then you can upgrade your version of `pip` from the absolutely-ancient version that ships with the CentOS 8 base image and it just works in my hands:

```
FROM centos:8
RUN dnf groupinstall -y "Development Tools"; dnf install -y python3-devel libjpeg-devel
RUN python3 -m pip install -U pip
RUN python3 -m pip install darshan
# python3 can import darshan
```

Also, try not to mix `pip` and `conda` (I see them mixed in your example above)--it can lead to headaches.

**Comment by tylerjereddy** [comment]
Otherwise you can look up the `USER` directive for `Dockerfile` and build up a user-based Python installation, which is likely even more robust (you should still upgrade `pip` to support recent `manylinux` binary wheel versions, etc.).

**Comment by dcsouthwick** [comment]
Thanks for your response. If I understand your example, the issue is actually outdated PIP (that generates hash in binary library) ? 

Yes, I pulled a fast one with that conda example! I tried to use pyDarshan with Jupyter notebooks  by pulling the latest jupyter from docker hub... it seems they use a newer python (3.9) and conda (hence the paste). Unfortunately, darshan is not available via conda it seems, so I tried with pip to test your example:
```
$ docker run -ti jupyter/minimal-notebook bash
(base) jovyan@92e480d1e0e8:~$ id
uid=1000(jovyan) gid=100(users) groups=100(users)
(base) jovyan@92e480d1e0e8:~$ pip --version
pip 21.3.1 from /opt/conda/lib/python3.9/site-packages/pip (python 3.9)

# OK unprivileged user install + newer pip 
(base) jovyan@92e480d1e0e8:~$ pip3 install --user darshan
(base) jovyan@92e480d1e0e8:~$ pip show darshan
Name: darshan
Version: 3.3.1.0
Summary: Python tools to interact with darshan log records of HPC applications.
Home-page: https://www.mcs.anl.gov/research/projects/darshan/
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/jovyan/.local/lib/python3.9/site-packages
Requires: cffi, matplotlib, numpy, pandas
Required-by:
(base) jovyan@92e480d1e0e8:~$ ls /home/jovyan/.local/lib/python3.9/site-packages/darshan.libs/
libdarshan-util-0ca4caca.so  libz-eb09ad1d.so.1.2.3
```

So it seems user (non-root) install has no effect here. What version of pip does darshan require?

**Comment by tylerjereddy** [comment]
Did you actually try importing `darshan`? The lib names are probably ok like that (that isn't really a problem if the import works).

`darshan` doesn't require a specific version of `pip`, but `manylinux` standard does, and there is extensive documentation on that stuff in the PEPs, but in short you can look at the version of `manylinux` used for our wheels here: 
https://pypi.org/project/darshan/#files

And then use an appropriate version of `pip`: https://stackoverflow.com/a/63137370/2942522

However, I can't really think of a good reason not to just do: a user install with the most recent stable version of `pip`.

**Comment by shanedsnyder** [comment]
Closing this old issue. I think Tyler was able to reproduce and ultimately workaround with a newer pip version. Feel free to re-open if there are other problems.
