### ISSUE TITLE
Darshan 3.2.1 deadlock in MPI_Finalize() in mpi_hello

### ISSUE THREAD

**Issue by morrone** [darshan-hpc/darshan#559]
We are seeing darshan deadlock in MPI_Finalize() with a simple mpi_hello program running with two tasks:

```
#include <stdio.h>
#include <mpi.h>

int main(int argc, char **argv)
{
int ret;
int numprocs, rank, len;

MPI_Init(&argc, &argv);
MPI_Comm_size(MPI_COMM_WORLD, &numprocs);
MPI_Comm_rank(MPI_COMM_WORLD, &rank);

if(rank==0)
{
printf("(master) [MPI process %d] of %d ranks\n", rank, numprocs);
}

MPI_Finalize();
return 0;
}
```

Compiled with mvapich2 (but I'm told that is not the only MPI library seeing this issue), we can see a two-node, two-process consistently gettting stuck like so:

Task 0:
```#0  0x00002aaaacc955ad in ips_ptl_poll () from /lib64/libpsm2.so.2
#1  0x00002aaaacc936c7 in psmi_poll_internal () from /lib64/libpsm2.so.2
#2  0x00002aaaacc8d308 in psm2_mq_ipeek2 () from /lib64/libpsm2.so.2
#3  0x00002aaaab20124c in psm_progress_wait (blocking=0) at src/mpid/ch3/channels/psm/src/psm_queue.c:247
#4  0x00002aaaab176647 in MPIC_Wait (request_ptr=0x0, errflag=0x0) at src/mpi/coll/helper_fns.c:296
#5  0x00002aaaab17643a in MPIC_Sendrecv (sendbuf=0x0, sendcount=0, sendtype=7834952, dest=7834936, sendtag=0, recvbuf=0x1, recvcount=1, recvtype=1275069445, source=1, recvtag=14,
    comm_ptr=0x2aaaab6f87a0 <MPID_Comm_direct>, status=0x1, errflag=0x7fffffffb564) at src/mpi/coll/helper_fns.c:558
#6  0x00002aaaab0c1f5c in MPIR_Allreduce_pt2pt_rd_MV2 (sendbuf=0x0, recvbuf=0x0, count=-1418754144, datatype=0, op=0, comm_ptr=0x1, errflag=0x7fff4c000405) at src/mpi/coll/allreduce_osu.c:395
#7  0x00002aaaab0bf94c in MPIR_Allreduce_index_tuned_intra_MV2 (sendbuf=0x0, recvbuf=0x0, count=7834952, datatype=7834936, op=0, comm_ptr=0x1, errflag=0x2) at src/mpi/coll/allreduce_osu.c:2602
#8  0x00002aaaab058f65 in MPIR_Allreduce_impl (sendbuf=0x0, recvbuf=0x0, count=7834952, datatype=7834936, op=0, comm_ptr=0x1, errflag=0x2aaaab6f8990 <MPID_Comm_direct+496>) at src/mpi/coll/allreduce.c:771
#9  0x00002aaaab10aabd in create_2level_comm (comm=0, size=0, my_rank=7834952) at src/mpi/comm/create_2level_comm.c:1029
#10 0x00002aaaab0e3033 in mv2_increment_shmem_coll_counter (comm_ptr=0x0) at src/mpi/coll/ch3_shmem_coll.c:1882
#11 0x00002aaaab0658a6 in PMPI_Reduce (sendbuf=0x0, sendbuf@entry=0xffffffffffffffff, recvbuf=0x0, count=7834952, count@entry=1, datatype=7834936, datatype@entry=1275069501, op=0, op@entry=1476395016, root=1,
    root@entry=0, comm=-2080374784) at src/mpi/coll/reduce.c:1263
#12 0x00002aaaaacda012 in darshan_log_write_header (core=0x66d1f0, core=0x66d1f0, log_fh=...) at lib/darshan-core.c:1735
#13 darshan_core_shutdown () at lib/darshan-core.c:638
#14 0x00002aaaaacd5c43 in MPI_Finalize () at lib/darshan-core-init-finalize.c:85
#15 0x0000000000401fbe in main ()
```

Task 1:

```
(gdb) bt
#0  0x00002aaaacc954c9 in ips_ptl_poll () from /lib64/libpsm2.so.2
#1  0x00002aaaacc936c7 in psmi_poll_internal () from /lib64/libpsm2.so.2
#2  0x00002aaaacc8d308 in psm2_mq_ipeek2 () from /lib64/libpsm2.so.2
#3  0x00002aaaab20124c in psm_progress_wait (blocking=7810816) at src/mpid/ch3/channels/psm/src/psm_queue.c:247
#4  0x00002aaaab176647 in MPIC_Wait (request_ptr=0x772f00, errflag=0x0) at src/mpi/coll/helper_fns.c:296
#5  0x00002aaaab17643a in MPIC_Sendrecv (sendbuf=0x772f00, sendcount=0, sendtype=5435404, dest=1, sendtag=0, recvbuf=0x30, recvcount=2, recvtype=1275069445, source=0, recvtag=7,
    comm_ptr=0x2aaaab6f87a0 <MPID_Comm_direct>, status=0x7fffffffb2e0, errflag=0x7fffffffb554) at src/mpi/coll/helper_fns.c:558
#6  0x00002aaaab0b8283 in MPIR_Allgather_RD_MV2 (sendbuf=0x772f00, sendcount=0, sendtype=5435404, recvbuf=0x1, recvcount=0, recvtype=48, comm_ptr=0x1, errflag=0x2aaaab6f87a0 <MPID_Comm_direct>)
    at src/mpi/coll/allgather_osu.c:553
#7  0x00002aaaab0b89db in MPIR_Allgather_index_tuned_intra_MV2 (sendbuf=0x772f00, sendcount=0, sendtype=5435404, recvbuf=0x1, recvcount=0, recvtype=48, comm_ptr=0x0,
    errflag=0x2aaaab0b80a2 <MPIR_Allgather_MV2+2114>) at src/mpi/coll/allgather_osu.c:2501
#8  0x00002aaaab0b80a2 in MPIR_Allgather_MV2 (sendbuf=0x772f00, sendcount=0, sendtype=5435404, recvbuf=0x1, recvcount=0, recvtype=48, comm_ptr=0x2, errflag=0x2aaaab0737f6 <MPIR_Allgather_impl+38>)
    at src/mpi/coll/allgather_osu.c:2556
#9  0x00002aaaab0737f6 in MPIR_Allgather_impl (sendbuf=0x772f00, sendcount=0, sendtype=5435404, recvbuf=0x1, recvcount=0, recvtype=48, comm_ptr=0x1, errflag=0x2aaaab10ab1c <create_2level_comm+700>)
    at src/mpi/coll/allgather.c:845
#10 0x00002aaaab10ab1c in create_2level_comm (comm=7810816, size=0, my_rank=5435404) at src/mpi/comm/create_2level_comm.c:1063
#11 0x00002aaaab0e3033 in mv2_increment_shmem_coll_counter (comm_ptr=0x772f00) at src/mpi/coll/ch3_shmem_coll.c:1882
#12 0x00002aaaab0588c9 in PMPI_Allreduce (sendbuf=0x772f00, sendbuf@entry=0xffffffffffffffff, recvbuf=0x0, recvbuf@entry=0x7fffffffb76c, count=5435404, count@entry=1, datatype=1, datatype@entry=1275069445,
    op=0, op@entry=1476395015, comm=48) at src/mpi/coll/allreduce.c:914
#13 0x00002aaaaacda7cb in darshan_core_shutdown () at lib/darshan-core.c:641
#14 0x00002aaaaacd5c43 in MPI_Finalize () at lib/darshan-core-init-finalize.c:85
#15 0x0000000000401fbe in main ()
```

We find that if we add a printf() ourside of the "if (rank==0)" the problem goes away.

**Comment by shanedsnyder** [comment]
Any chance you could try out a more recent release? Maybe 3.3.1? I see in our changelog we fixed a deadlock that appeared to affect mvapich2 applications at Darshan shutdown time (fix applied as part of 3.3.0-pre1 release), so I'm hoping this one has already been resolved. If not, I can definitely have a closer look to see what's going on.

**Comment by morrone** [comment]
Is that commit f8d57542b6b37f9e2d8ccc75f88a82efa4171b4e? It may be easier to patch than upgrade at the moment.

**Comment by shanedsnyder** [comment]
The commit I had in mind is 14d7469, but looking closer at your code and the backtrace, I doubt it's the culprit actually. Could you share what mvapich2 version you're using so I could try to reproduce?

**Comment by shanedsnyder** [comment]
...actually, that bug fix could actually be applicable. Sorry about the indecisiveness, but I forgot that we do track printf calls in Darshan. I was thinking that your reproducer didn't actually do any I/O, but that printf call should be tracked. I'm not sure I understand in what cases the printf leads to a hang from your description, but if it hangs when all ranks do the printf, it could point to an issue with Darshan's handling of shared records (which the above bug may have fixed).

**Comment by morrone** [comment]
Oh sorry, yes, commit 14d7469. The f8d57 commit is my local cherry-picked version of that.

It was _not_ handing when all tasks did printf, it only hangs with the provided example where only task 0 does printf.

But commit 14d7469 _does_ appear to have fixed the problem. I can no longer reproduce the hang with that patch in place.

**Comment by shanedsnyder** [comment]
Ah, great, thanks for trying that out and confirming that fix! I was skeptical because the backtrace pointed to another point in the code, but maybe the hang doesn't manifest until running some collective operations after the original error. From your description, my guess is that bug was leading rank 0 to try to run a reduction operation, but rank 1 never participated in it, eventually causing some deadlock.

Please let us know if you run into any more issues or if you notice this issue isn't quite resolved.
