### ISSUE TITLE
segfault in darshan-parser if old darshan-utils encounters a new module

### ISSUE THREAD

**Issue by carns** [darshan-hpc/darshan#621]
reported by @jakobluettgau

This can be reproduced by running darshan-parser from the most recent Darshan release on a log file that contains heatmap data.

In theory this should be fine; the parser is meant to ignore unknown module types.  It looks like the problem is in a for loop that accesses an array of module names.

**Comment by carns** [comment]
A little more information here.  Depending on compiler/architecture/etc. this won't necessarily produce a segfault, and valgrind won't detect it because the problem with an access beyond the end of a statically-declared global array.  Address sanitizer can reliably detect it, though (this was collected with a Darshan 3.3.1 build, so the line numbers map there):

```
==3370002==ERROR: AddressSanitizer: global-buffer-overflow on address 0x561aec915490 at pc 0x561aec8a8e50 bp 0x7ffc080301f0 sp 0x7ffc080301e0
READ of size 8 at 0x561aec915490 thread T0
    #0 0x561aec8a8e4f in main ../darshan-parser.c:337
    #1 0x7f068dedefcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #2 0x7f068dedf07c in __libc_start_main_impl ../csu/libc-start.c:409
    #3 0x561aec8a7a64 in _start (/home/carns/working/src/darshan/darshan/darshan-util/build/darshan-parser+0x19a64)

0x561aec915490 is located 48 bytes to the left of global variable 'darshan_module_names' defined in '../../darshan-log-format.h:188:27' (0x561aec9154c0) of size 112
0x561aec915490 is located 0 bytes to the right of global variable 'darshan_module_names' defined in '../../darshan-log-format.h:188:27' (0x561aec915420) of size 112
```
This is in a loop in the darshan-parser that looks like this:
```
    for(i=0; i<DARSHAN_MAX_MODS; i++)
    {
        if(fd->mod_map[i].len || DARSHAN_MOD_FLAG_ISSET(fd->partial_flag, i))
        {
            printf("# %s module: %zu bytes (compressed), ver=%d\n",
                darshan_module_names[i], fd->mod_map[i].len, fd->mod_ver[i]);
        }
    }
```
The problem is that `MAX_MODS` has a fixed value of 16.  The `darshan_module_names[]` array is defined in darshan-log-format.h with an X macro, and is only as long as the number of defined modules.    The number of defined modules varies from release to release.  So if someone looks up a module with a id less than `MAX_MODS` but greater than the number that were available in a given darshan build, then they will run beyond the end of the array.  This may be a problem in other locations and also with the `darshan_module_versions[]` array.

We need to either define the length of those arrays or else put a sentinel entry at the end of the array.

Unfortunately we can't do anything about  Darshan <= 3.3.1 hitting this problem, but we can fix it moving forward.

**Comment by carns** [comment]
This is somewhat related to #667 because we happen to be near the limit on the number of modules that can be defined in the current log format also.

**Comment by carns** [comment]
We don't need a sentinel value; it should be possible with X macros to just add a final enum value that automatically ends up being set to the array length as modules are added to the list.  I'll try that.
