### ISSUE TITLE
pydarshan: log with no data inside still reports POSIX as available record

### ISSUE THREAD

**Issue by bebosudo** [darshan-hpc/darshan#773]
Hi, we're doing some data analysis on darshan log files, and we noticed that we can't rely on `report.counters` or `report.records` to iterate over the records, because some logfiles are empty but still show POSIX records being available:
```python
>>> import darshan
>>> report = darshan.DarshanReport("empty_log.darshan")
>>> report.records
{'POSIX': <darshan.report.DarshanRecordCollection object at 0x15553bb75d90>}
>>> report.counters
{'POSIX': {'counters': ['POSIX_OPENS', 'POSIX_FILENOS', .., 'POSIX_SLOWEST_RANK_BYTES'], 'fcounters': ['POSIX_F_OPEN_START_TIMESTAMP', .., 'POSIX_F_VARIANCE_RANK_BYTES']}}
>>> report.records["POSIX"]
<darshan.report.DarshanRecordCollection object at 0x15553bb75d90>
>>> report.records["POSIX"].to_df()
Traceback (most recent call last):
  File "~/.conda/envs/darshan340env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'counters'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.conda/envs/darshan340env/lib/python3.9/site-packages/darshan/report.py", line 280, in to_df
    df = pd.DataFrame(np.stack(df_recs[ct_key].to_numpy()), columns=cols)
  File "~/.conda/envs/darshan340env/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "~/.conda/envs/darshan340env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'counters'
>>>
```

I also tried obfuscating the log but I think the utility recognizes that it's an empty file and strips it of unneeded counters:

```python
>>> report = darshan.DarshanReport("empty_log.darshan.converted")
>>> report.records
{}
>>> report.counters
{}
```

CC @jeanbez

**Comment by jakobluettgau** [comment]
The best member to check would actually be `report.modules`, but I assume the POSIX module is actually present, and as a result the `report.counters` and `report.records` are populated for POSIX.

Can you double check if the count in `report.modules["POSIX"]` is meaningful?


If it is a non-zero positive count, are you able to access the first record?

```
report.records["POSIX"][0]
```

**Comment by bebosudo** [comment]
Good point on `report.modules`, we'll switch our script to using that to iterate over existing records.
Unfortunately I can't access any record:

```python
>>> import darshan
>>> report = darshan.DarshanReport("empty_log.darshan")
>>> report.modules
{'POSIX': {'len': 414, 'ver': 1, 'idx': 1, 'partial_flag': False, 'num_records': 0}}
>>> report.records["POSIX"]
<darshan.report.DarshanRecordCollection object at 0x15553bb76b50>

>>> report.records["POSIX"][0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/c/chiusole/.conda/envs/darshan340env/lib/python3.9/site-packages/darshan/report.py", line 102, in __getitem__
    record.append(self._records[key])
IndexError: list index out of range

>>> report.records["POSIX"].info()
Module:       POSIX
Records:      0
Coll. Type:   collection
Ranks:        set()
Name Records: set()

>>> report.records["POSIX"]._records
[]
```

I guess this is a "problem" in the particular input darshan log file (which I sent to Shane Snyder over NERSC-internal communication), which pydarshan exposes it to the user as it is, but maybe some checks could be introduced?
We'll add an if on `num_records` for each module, but I think it would be useful for pydarshan to do that internally.

It seems that the first four items in `report.modules[mod]` are set in darshan/backend/cffi_backend.py in `log_get_modules()`, while the `num_records` key is set in darshan/report.py in `mod_read_all_records()`.
I added a breakpoint in `log_get_modules()` but there's no records data available in that function to add an if on, to avoid creating an empty module, so a "fix" may be more complex than I thought.

**Comment by jakobluettgau** [comment]
Would you prefer a always pre-populated "num_records" key with None for example? 

Unfortunately, the total number of records can only be determined after scanning all records for a darshan log, which is why this "logic" is seemingly scattered across different places.

**Comment by bebosudo** [comment]
> Would you prefer a always pre-populated "num_records" key with None for example?

I feel like that wouldn't help, since we `read_all=True` when loading a DarshanReport anyway.

Maybe we could introduce an iterator over the report object? In this way we could add some after-loading logic there. That could be coded like:

```python
class DarshanReport:
    ...
    def __iter__(self):
        return iter({mod: data for mod, data in self.modules.items()
                               if "num_records" in data and data["num_records"] > 0})
```

So the user could do:
```python
import darshan
report = darshan.DarshanReport(darshan_file)
for mod in report:  # only modules with actual records are returned
    # now it's safe to use mod to iterate over records or counters
    print(mod, report.modules[mod], report.records[mod].to_list())
```

Iterating over DarshanReport would make sense only when records have been loaded into the report and therefore `num_records` is present, and we would return the module and its records only when records are a positive amount.
What do you think?
